#include <stdio.h>
#include <locale.h>
#include <string.h>
void main(){
    setlocale(LC_ALL,"Portuguese");
int z,x=0,y=4;
    printf("*==*==*==*==*==*==*==*==*==*==\n");
    printf("\tExercícios\n");
    printf("\n");
    printf("*==*==*==*==*==*==*==*==*==*==\n");
    printf("\tNORMAL\n");
    printf("*==*==*==*==*==*==*==*==*==*==\n");
    printf("o valor NORMAL de x é \"%d\"\n",x);
    printf("o valor NORMAL de y é \"%d\"\n",y);
    z=x+y;
    printf("O valor de z=\"%d\"+\"%d\" \"%d\"\n",x,y,z);
    printf("\n");
    printf("*==*==*==*==*==*==*==*==*==*==\n");
    printf("    PRÉ INCREMENTO\n");
    printf("*==*==*==*==*==*==*==*==*==*==\n");
    printf("o valor PRÉ INCREMENTO de x é \"%d\"\n",++x);
    printf("o valor PRÉ INCREMENTO de y é \"%d\"\n",++y);
    z=x+y;
    printf("O valor de z=\"%d\"+\"%d\" \"%d\"\n",x,y,z);
    printf("\n");
    printf("\n");
    printf("*==*==*==*==*==*==*==*==*==*==\n");
    printf("\tNORMAL\n");
    printf("*==*==*==*==*==*==*==*==*==*==\n");
    printf("o valor NORMAL de x é \"%d\"\n",--x);
    printf("o valor NORMAL de y é \"%d\"\n",--y);
    z=x+y;
    printf("O valor de z=\"%d\"+\"%d\" \"%d\"\n",x,y,z);
    printf("\n");
    printf("*==*==*==*==*==*==*==*==*==*==\n");
    printf("\tPRÉ DECREMENTO\n");
    printf("*==*==*==*==*==*==*==*==*==*==\n");
    printf("o valor PRÉ DECREMENTO de x é \"%d\"\n",--x);
    printf("o valor PRÉ DECREMENTO de y é \"%d\"\n",--y);
    z=x+y;
    printf("O valor de z=\"%d\"+\"%d\" \"%d\"\n",x,y,z);
    printf("\n");
    printf("\n");
    printf("*==*==*==*==*==*==*==*==*==*==\n");
    printf("\tNORMAL\n");
    printf("*==*==*==*==*==*==*==*==*==*==\n");
    printf("o valor NORMAL de x é \"%d\"\n",++x);
    printf("o valor NORMAL de y é \"%d\"\n",++y);
    z=x+y;
    printf("O valor de z=\"%d\"+\"%d\" \"%d\"\n",x,y,z);
    printf("\n");
    printf("\n");
    printf("*==*==*==*==*==*==*==*==*==*==\n");
    printf("    PÓS INCREMENTO\n");
    printf("*==*==*==*==*==*==*==*==*==*==\n");
    printf("o valor PRÉ INCREMENTO de x é \"%d\"\n",x++);
    printf("o valor PRÉ INCREMENTO de y é \"%d\"\n",y++);
    z=x+y;
    printf("O valor de z=\"%d\"+\"%d\" \"%d\"\n",x,y,z);
    printf("\n");
    printf("\n");
    printf("*==*==*==*==*==*==*==*==*==*==\n");
    printf("\tNORMAL\n");
    printf("*==*==*==*==*==*==*==*==*==*==\n");
    printf("o valor NORMAL de x é \"%d\"\n",--x);
    printf("o valor NORMAL de y é \"%d\"\n",--y);
    z=x+y;
    printf("O valor de z=\"%d\"+\"%d\" \"%d\"\n",x,y,z);
    printf("\n");
    printf("\n");
    printf("*==*==*==*==*==*==*==*==*==*==\n");
    printf("    PÓS DECREMENTO\n");
    printf("*==*==*==*==*==*==*==*==*==*==\n");
    printf("o valor PRÉ INCREMENTO de x é \"%d\"\n",x--);
    printf("o valor PRÉ INCREMENTO de y é \"%d\"\n",y--);
    z=x+y;
    printf("O valor de z=\"%d\"+\"%d\" \"%d\"\n",x,y,z);

}
